version: '3.1'
services:
  wordpress:
    # user: "${UID}:${GID}"
    build:
      context: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: ${SITE_DB_HOST}
      WORDPRESS_DB_USER: ${SITE_DB_USER}
      WORDPRESS_DB_PASSWORD: ${SITE_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${SITE_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
  mysql:
    image: mysql
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-false}
